kind: pipeline
type: docker
name: nodejs
steps:
- name: build
  image: node:latest
  environment:
    MONGO_CONNEXION_URI: mongodb://mongo:27017/midgar-test?connectTimeoutMS=1000"
  commands:
    - yarn
    - yarn run coverage:ci
    - yarn run eslint:ci
- name: sonar
  image: fmetais/drone-sonar-scan-plugin:latest
  settings:
    sonar.host.url: 
      from_secret: sonar_host
    sonar.login: 
      from_secret: sonar_token
services:
- name: mongo
  image: mongo:4
  ports:
  - 27017
